//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Extrupet.DAL.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ExtrupetEntities : DbContext
    {
        public ExtrupetEntities()
            : base("name=ExtrupetEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CompanySetup> CompanySetups { get; set; }
        public virtual DbSet<GradeMaster> GradeMasters { get; set; }
        public virtual DbSet<GradeTypeMaster> GradeTypeMasters { get; set; }
        public virtual DbSet<GradeWiseQualityParameterBaseData> GradeWiseQualityParameterBaseDatas { get; set; }
        public virtual DbSet<ProductMaster> ProductMasters { get; set; }
        public virtual DbSet<QualityMeasurementUnitMaster> QualityMeasurementUnitMasters { get; set; }
        public virtual DbSet<QualityParameterMaster> QualityParameterMasters { get; set; }
        public virtual DbSet<TestMethodMaster> TestMethodMasters { get; set; }
        public virtual DbSet<UserMaster> UserMasters { get; set; }
        public virtual DbSet<UserRoleMaster> UserRoleMasters { get; set; }
    }
}
