//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Extrupet.DAL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class GradeWiseQualityParameterBaseData
    {
        public int BaseDataId { get; set; }
        public byte GradeId { get; set; }
        public short QualityParameterId { get; set; }
        public string BaseValue { get; set; }
        public Nullable<byte> TestMethodId { get; set; }
        public System.DateTime LastUpdatedOnUTC { get; set; }
        public System.Guid LastUpdatedBy { get; set; }
    
        public virtual GradeMaster GradeMaster { get; set; }
        public virtual QualityParameterMaster QualityParameterMaster { get; set; }
        public virtual TestMethodMaster TestMethodMaster { get; set; }
    }
}
