//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Extrupet.DAL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class GradeMaster
    {
        public byte GradeId { get; set; }
        public string GradeName { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime LastUpdatedOnUTC { get; set; }
        public int LastUpdatedBy { get; set; }
    
        public virtual UserMaster UserMaster { get; set; }
    }
}
