//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Extrupet.DAL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductMaster
    {
        public System.Guid ProductId { get; set; }
        public string ProductName { get; set; }
        public System.DateTime LastUpdatedOnUTC { get; set; }
        public byte GradeTypeId { get; set; }
        public System.Guid LastUpdatedBy { get; set; }
    
        public virtual GradeTypeMaster GradeTypeMaster { get; set; }
    }
}
