//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Extrupet.DAL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class QualityParameterMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QualityParameterMaster()
        {
            this.GradeWiseQualityParameterBaseDatas = new HashSet<GradeWiseQualityParameterBaseData>();
        }
    
        public short QualityParameterId { get; set; }
        public string QualityParameterName { get; set; }
        public byte QualityMeasurementUnitId { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime LastUpdatedOnUTC { get; set; }
        public System.Guid LastUpdatedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GradeWiseQualityParameterBaseData> GradeWiseQualityParameterBaseDatas { get; set; }
        public virtual QualityMeasurementUnitMaster QualityMeasurementUnitMaster { get; set; }
    }
}
