//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Extrupet.DAL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMaster
    {
        public System.Guid UserId { get; set; }
        public byte RoleId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmailId { get; set; }
        public string EmployeeId { get; set; }
        public string Password { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime LastUpdatedOnUTC { get; set; }
        public System.Guid LastUpdatedBy { get; set; }
    
        public virtual UserRoleMaster UserRoleMaster { get; set; }
    }
}
